/**
 * The drugs a mission prescribes, and the other names people call them by.
 *
 * Two lists, and the distinction matters. DRUGS is what the field offers and what
 * gets stored: one canonical name per molecule. DRUG_ALIASES is everything else a
 * clinician might type for the same thing -- a brand, or the name used on the
 * other side of the Atlantic -- which resolves to the canonical name on the way
 * in. A mission still carries drugs neither list knows, and those go in exactly
 * as typed; see DrugSelector.
 *
 * Why aliases at all: the medication report groups by the stored name, so every
 * spelling of one molecule is a separate row in it. Before this, Paracetamol,
 * Acetaminophen and Tylenol split 71 prescriptions of the same drug three ways,
 * and the first two split because the list offered both.
 *
 * Paracetamol is the canonical one: it is the international nonproprietary name,
 * and it was already the majority spelling in this database. Anyone who types
 * Acetaminophen or Tylenol still finds it -- the row simply reads Paracetamol.
 *
 * What is not here is as deliberate as what is. The list was 444 entries carrying
 * CAR-T therapy, withdrawn COVID antibodies, IV anaesthetics, clotting factors
 * and forty cytotoxics -- none of which a field clinic dispenses, and all of
 * which the near-match search had to compete against. Of those 444, 44 had ever
 * been used. Pruning them is what makes room for the drugs that were missing:
 * metformin, aspirin, cephalexin, salbutamol, ORS, artemether/lumefantrine,
 * and -- for the dentistry this app was built around -- articaine and
 * chlorhexidine.
 *
 * Built once at module scope rather than per call: a fresh array each time would
 * invalidate the memo that decides which drugs the autocomplete shows, so the
 * near-match search would rerun on every keystroke.
 */

export const DRUGS = [
  "Acetylcysteine",
  "Acyclovir",
  "Albendazole",
  "Alendronate",
  "Alprazolam",
  "Amantadine",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Amoxicillin/Clavulanate",
  "Apixaban",
  "Aprepitant",
  "Artemether/Lumefantrine",
  "Articaine",
  "Aspirin",
  "Atenolol",
  "Atorvastatin",
  "Atovaquone/Proguanil",
  "Atropine",
  "Azithromycin",
  "Bacitracin",
  "Beclomethasone",
  "Benzocaine",
  "Betamethasone",
  "Bisoprolol",
  "Budesonide",
  "Bupivacaine",
  "Calcium Carbonate",
  "Canagliflozin",
  "Carbamazepine",
  "Carvedilol",
  "Cefazolin",
  "Cefdinir",
  "Cefotaxime",
  "Cefoxitin",
  "Ceftazidime",
  "Ceftriaxone",
  "Cefuroxime",
  "Celecoxib",
  "Cephalexin",
  "Cetirizine",
  "Chlorhexidine",
  "Chloroquine",
  "Chlorpheniramine",
  "Chlorpromazine",
  "Chlorpropamide",
  "Cholecalciferol",
  "Cholestyramine",
  "Cilostazol",
  "Ciprofloxacin",
  "Clindamycin",
  "Clofazimine",
  "Clomiphene",
  "Clonazepam",
  "Clonidine",
  "Clopidogrel",
  "Clotrimazole",
  "Clozapine",
  "Colchicine",
  "Conjugated Estrogens",
  "Cyclobenzaprine",
  "Dapagliflozin",
  "Dexamethasone",
  "Diazepam",
  "Diclofenac",
  "Digoxin",
  "Diltiazem",
  "Diphenhydramine",
  "Donepezil",
  "Doxazosin",
  "Doxycycline",
  "Dronabinol",
  "Drospirenone",
  "Dulaglutide",
  "Duloxetine",
  "Dutasteride",
  "Edoxaban",
  "Enalapril",
  "Enoxaparin",
  "Eplerenone",
  "Erythromycin",
  "Esomeprazole",
  "Estradiol",
  "Estradiol Valerate",
  "Ethambutol",
  "Etonogestrel",
  "Eugenol",
  "Exenatide",
  "Famciclovir",
  "Famotidine",
  "Febuxostat",
  "Felodipine",
  "Fentanyl",
  "Ferrous Sulfate",
  "Finasteride",
  "Fluconazole",
  "Fludrocortisone",
  "Fluoxetine",
  "Fluphenazine",
  "Fluticasone",
  "Folic Acid",
  "Formoterol",
  "Fosaprepitant",
  "Fosinopril",
  "Furosemide",
  "Gabapentin",
  "Ganciclovir",
  "Gemifloxacin",
  "Gentamicin",
  "Glimepiride",
  "Glipizide",
  "Glucagon",
  "Glyburide",
  "Granisetron",
  "Griseofulvin",
  "Haloperidol",
  "Heparin",
  "Hydrochlorothiazide",
  "Hydrocodone/Acetaminophen",
  "Hydrocortisone",
  "Hydromorphone",
  "Hydroxychloroquine",
  "Hydroxyzine",
  "Ibuprofen",
  "Isoniazid",
  "Isradipine",
  "Itraconazole",
  "Ivabradine",
  "Ivermectin",
  "Labetalol",
  "Lacosamide",
  "Lamotrigine",
  "Levodopa",
  "Levofloxacin",
  "Levonorgestrel",
  "Levothyroxine",
  "Lidocaine",
  "Linezolid",
  "Lisinopril",
  "Lithium",
  "Loperamide",
  "Loratadine",
  "Lorazepam",
  "Losartan",
  "Luliconazole",
  "Lurasidone",
  "Mebendazole",
  "Medroxyprogesterone",
  "Mefloquine",
  "Memantine",
  "Mepivacaine",
  "Mesalamine",
  "Metamizole",
  "Metformin",
  "Methadone",
  "Methimazole",
  "Methylprednisolone",
  "Metoclopramide",
  "Metoprolol",
  "Metronidazole",
  "Miconazole",
  "Minocycline",
  "Minoxidil",
  "Modafinil",
  "Montelukast",
  "Morphine",
  "Moxifloxacin",
  "Multivitamin",
  "Naloxone",
  "Naproxen",
  "Natamycin",
  "Niacin",
  "Niclosamide",
  "Nifedipine",
  "Nimodipine",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Norethindrone",
  "Norgestimate",
  "Nortriptyline",
  "Nystatin",
  "Ofloxacin",
  "Olanzapine",
  "Olopatadine",
  "Omeprazole",
  "Ondansetron",
  "Oral Rehydration Salts",
  "Oseltamivir",
  "Oxazepam",
  "Oxcarbazepine",
  "Oxiconazole",
  "Oxycodone/Acetaminophen",
  "Palonosetron",
  "Pantoprazole",
  "Paracetamol",
  "Paroxetine",
  "Penicillin V",
  "Pentoxifylline",
  "Permethrin",
  "Phenazopyridine",
  "Phenytoin",
  "Pioglitazone",
  "Piperacillin/Tazobactam",
  "Posaconazole",
  "Potassium Iodide",
  "Praziquantel",
  "Prazosin",
  "Prednisolone",
  "Prednisone",
  "Prenatal Vitamin",
  "Prilocaine",
  "Primaquine",
  "Prochlorperazine",
  "Promethazine",
  "Propylthiouracil",
  "Protriptyline",
  "Pyrimethamine",
  "Quetiapine",
  "Quinine",
  "Rabeprazole",
  "Ramipril",
  "Repaglinide",
  "Rifabutin",
  "Rifampin",
  "Rifapentine",
  "Risedronate",
  "Rivaroxaban",
  "Rizatriptan",
  "Ropivacaine",
  "Rosiglitazone",
  "Rosuvastatin",
  "Roxithromycin",
  "S-Adenosylmethionine (SAMe)",
  "Salbutamol",
  "Saline Eye Drops",
  "Selegiline",
  "Semaglutide",
  "Simvastatin",
  "Sitagliptin",
  "Sodium Fluoride",
  "Spironolactone",
  "Streptomycin",
  "Sulconazole",
  "Sulfamethoxazole/Trimethoprim",
  "Sulfasalazine",
  "Terazosin",
  "Terbinafine",
  "Terbutaline",
  "Testosterone",
  "Thioridazine",
  "Ticagrelor",
  "Tiotropium",
  "Tolnaftate",
  "Topiramate",
  "Tramadol",
  "Tranexamic Acid",
  "Trazodone",
  "Triamcinolone",
  "Triamterene",
  "Triazolam",
  "Trihexyphenidyl",
  "Trimethoprim",
  "Valacyclovir",
  "Valganciclovir",
  "Valsartan",
  "Vardenafil",
  "Venlafaxine",
  "Verapamil",
  "Vitamin A",
  "Voriconazole",
  "Warfarin",
  "Zinc Sulfate",
  "Zoledronic Acid",
  "Zolmitriptan",
  "Zolpidem",
] as const;

/** Anything else the same molecule gets called, mapped to its DRUGS entry. */
export const DRUG_ALIASES: Record<string, string> = {
  "Acetaminophen": "Paracetamol",
  "Acetylsalicylic Acid": "Aspirin",
  "Advil": "Ibuprofen",
  "Albuterol": "Salbutamol",
  "ASA": "Aspirin",
  "Augmentin": "Amoxicillin/Clavulanate",
  "Bactrim": "Sulfamethoxazole/Trimethoprim",
  "Benadryl": "Diphenhydramine",
  "Brufen": "Ibuprofen",
  "Cipro": "Ciprofloxacin",
  "Claritin": "Loratadine",
  "Co-trimoxazole": "Sulfamethoxazole/Trimethoprim",
  "Coartem": "Artemether/Lumefantrine",
  "Diflucan": "Fluconazole",
  "Dipirona": "Metamizole",
  "Dipyrone": "Metamizole",
  "Flagyl": "Metronidazole",
  "Glucophage": "Metformin",
  "Keflex": "Cephalexin",
  "Losec": "Omeprazole",
  "Motrin": "Ibuprofen",
  "Ora-Gel": "Benzocaine",
  "Panadol": "Paracetamol",
  "Peridex": "Chlorhexidine",
  "Prilosec": "Omeprazole",
  "Tegretol": "Carbamazepine",
  "Trimethoprim/Sulfamethoxazole": "Sulfamethoxazole/Trimethoprim",
  "Tums": "Calcium Carbonate",
  "Tylenol": "Paracetamol",
  "Ventolin": "Salbutamol",
  "Vermox": "Mebendazole",
  "Voltaren": "Diclofenac",
  "Zantac": "Famotidine",
  "Zithromax": "Azithromycin",
  "Zyrtec": "Cetirizine",
};

const byLookupName = new Map<string, string>([
  ...DRUGS.map((drug) => [drug.toLowerCase(), drug] as const),
  ...Object.entries(DRUG_ALIASES).map(
    ([alias, canonical]) => [alias.toLowerCase(), canonical] as const
  ),
]);

// Every canonical drug plus every alias, so typing "Tyl" or "Coartem" finds
// something. Selecting an alias stores the canonical name, which is what
// resolveDrugName below is for.
const drugOptions = [...DRUGS, ...Object.keys(DRUG_ALIASES)]
  .sort((a, b) => a.localeCompare(b))
  .map((drug) => ({ id: drug, name: drug }));

/** The list the drug field offers. Stable across calls -- see the note above. */
export const getDrugOptions = () => drugOptions;

/**
 * The name to store for what was typed, or undefined if nothing is known by it.
 *
 * Case and surrounding space are ignored, so one drug is never filed under two
 * spellings. Undefined is not a rejection: the caller keeps the typed name, which
 * is how a mission records something neither list has heard of.
 */
export const resolveDrugName = (typed?: string) =>
  byLookupName.get((typed ?? "").trim().toLowerCase());
